// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xriunkrdrodfbgblufpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyaXVua3Jkcm9kZmJnYmx1ZnBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NzAwMzEsImV4cCI6MjA2NzA0NjAzMX0.NN1jvV4ThoAJjyitUcRWLasfOI6T7aDvpQl6NaC0aHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});